### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/TweetSets#53]
Update with new configuration changes and any installation changes.

Also change repository URL to https://github.com/gwu-libraries/TweetSets.git

**Comment by dolsysmith** [comment]
Could use a line `mkdir dataset_loading` in the instructions for creating the other storage directories. It appears in the `.env` but it's not specified that the user should create it. If this step is skipped, `docker-compose` creates it but with the wrong permissions.

**Comment by dolsysmith** [comment]
Might also be helpful, as part of the README, to include a more schematic overview of how the components of the application fit together.

**Comment by lwrubel** [comment]
Update the example spark-submit commands to reference the TweetSets-2.0.
