### ISSUE TITLE
Add text near Created at (from/to) fields to specify time, and time zone

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/TweetSets#80]
We should also specify that the dates are inclusive.  Something along the lines of:

Created from/to dates will include all tweets created within the date range, including the first and last dates.  Twitter records a tweet as having been created on a date if it was created between 0:00:00 and 23:59:59 on that date in the UTC+0 time zone.

**Comment by lwrubel** [comment]
Could be worked on with #87.
