### ISSUE TITLE
Request user's email when creating export

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/TweetSets#94]

**Comment by dolsysmith** [comment]
Should save email to dataset_params.json file for ease of retrieval.

**Comment by dolsysmith** [comment]
Saves the user's email address to `dataset_params.json` on first data extract. If the user requests an additional extract from the same dataset ID, and if they provide an email address, this address is saved to the file, overwriting the previous.

**Comment by dolsysmith** [comment]
Emails the user on completion of the data extract.
